### PR TITLE
Make mpi and zmq/grpc optional

### PR DESCRIPTION
**Pull request by erikzenker**
The usage of graybat changed a little bit:

* You include graybat via the umbrella header: `#include <graybat/graybat.hpp>`
* graybat provides compile time definitions 
  * graybat_ZMQ_CP_ENABLED
  * graybat_BMPI_CP_ENABLED
* If the graybat cmake config finds ZMQ then the particular definition will be set (the same is true for mpi)

### CODE REVIEW

**Comment by ax3l** [comment]
@erikzenker can you please provide a PR description, e.g. how to enable/disable the optional dependencies now? :)

**Comment by erikzenker** [comment]
CI is currently not working, I think it will be the best to provide a spack based ci once the spack package works properly

**Comment by ax3l** [comment]
@fabian-jung can you please review this? would be awesome if we could make the backend optional and reduce the install burden with it

**Comment by ax3l** [comment]
@erikzenker can we go on with this PR pls? :)

**Comment by erikzenker** [comment]
Sure, I was just waiting for fabian.

**Pull request merged**
